### ISSUE TITLE
Add CI for macOS and Windows

### ISSUE THREAD

**Issue by dvzrv** [jackaudio/jack-example-tools#11]
The current github workflows only test against jack1 and jack2 on Linux.
This needs to be extended to also include macOS and Windows (using whichever combination of jack implementations is sensible there).

- [x] macOS (#72)
- [x] Windows

**Comment by falkTX** [comment]
This is fixed by #75 
Though a few things had to be disabled in the build, related to alloca.

**Comment by falkTX** [comment]
Done in 2f7741700d9b22afe91987b56fe2967b387987bb
