### ISSUE TITLE
manpages are generated during configure step instead of build

### ISSUE THREAD

**Issue by falkTX** [jackaudio/jack-example-tools#39]

**Comment by dvzrv** [comment]
I don't think there is an alternative to [meson.add_postconf_script()](https://mesonbuild.com/Reference-manual_builtin_meson.html#mesonadd_postconf_script) and it is actually the correct place for generating the man pages, as the "build" is done by ninja (the man pages are not compiled, only modified using sed).

**Comment by dvzrv** [comment]
With https://github.com/jackaudio/jack-example-tools/commit/7ece4d2e2effa0a8b4448628ca9201980d023222 this is now taken care of in a call to `configure_file()` and does not require any external scripts anymore.
