### ISSUE TITLE
Incorporate fixes from example-clients and tools repository pull requests

### ISSUE THREAD

**Issue by falkTX** [jackaudio/jack-example-tools#43]
See https://github.com/jackaudio/example-clients/pulls and https://github.com/jackaudio/tools/pulls

We should merge as relevant, close as wont-fix/merge otherwise.

**Comment by dvzrv** [comment]
From what I can tell the following are good and should be added/ adapted to be added in case they are still needed:

* [ ] https://github.com/jackaudio/example-clients/pull/4
* [ ] https://github.com/jackaudio/example-clients/pull/5
* [ ] https://github.com/jackaudio/tools/pull/4
* [ ] https://github.com/jackaudio/tools/pull/7
* [ ] https://github.com/jackaudio/tools/pull/8
* [ ] https://github.com/jackaudio/tools/pull/11

I can't say whether https://github.com/jackaudio/example-clients/pull/6 is useful or not.
https://github.com/jackaudio/tools/pull/5 can be closed as won't fix (as we will not continue using autotools).

**Comment by dvzrv** [comment]
I think all related PRs in the other repos can be closed now and the repositories archived.
