### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by fpesari** [jackaudio/jack-example-tools#67]
Hello,

could you please adopt semantic versioning rather than current version 1? It would help packagers. Thanks.

**Comment by falkTX** [comment]
We already decided against it. We will follow a style similar to what systemd does, just incrementing a number.
It is really all semantics ;)

We are not counting on doing bugfix-only releases, that is, having main/master and stable/hotfix branches, instead it is all or nothing.
