### ISSUE TITLE
New release for Homebrew formula

### ISSUE THREAD

**Issue by nandahkrishna** [jackaudio/jack-example-tools#76]
Hi, I'm a Homebrew maintainer and I'm working on a new Homebrew formula for jack-example-tools, as it's been separated from jack. Support for building on macOS was added in #72, and this was created/merged after the [latest release](https://github.com/jackaudio/jack-example-tools/releases/tag/2). Homebrew prefers that new formulae do not have patches applied to them (an audit will fail if a new formula is patched), so it would be great to have a new release with these changes. Relevant discussion is in Homebrew/homebrew-core#99640. Thanks!

**Comment by nandahkrishna** [comment]
Yes, it builds successfully without patches using HEAD.

**Comment by falkTX** [comment]
Release is tagged https://github.com/jackaudio/jack-example-tools/releases/tag/3

**Comment by nandahkrishna** [comment]
https://github.com/Homebrew/homebrew-core/pull/99640 was merged (with the temporary fix for the example tools). A subsequent PR updated `jack` to 1.9.22 (https://github.com/Homebrew/homebrew-core/pull/122566), where the example tools were removed from the `jack` formula. I was unable to find time to debug the PR to create a separate `jack-example-tools` formula, but feel free to open a PR if you are willing (you could look at https://github.com/Homebrew/homebrew-core/pull/100262 as a starting point).
